kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-backend-canary
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: demo
        role: backend
        env: canary
    spec:
      containers:
      - name: backend
        image: gcr.io/devtestdb/demo:v1
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080