kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-backend-canary
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: demo
        role: backend
        env: canary
    spec:
      containers:
      - name: backend
        image: gcr.io/gkebinaryattz/demo:v1
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
      # [END cloud_sql_proxy_k8s_container]