kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-backend-production
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: demo
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: gcr.io/gkebinaryattz/demo@sha256:4e552bf5bbdfb24e0ccbbf0d824c84604f35f7be748eb662d016b09ae0e94fa3
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        # command: ["sh", "-c", "app -port=8080"]