kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-backend-production
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: demo
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: gcr.io/two-tier-app-gke/demo:v1
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        # command: ["sh", "-c", "app -port=8080"]